// services/ai.service.js
const { GoogleGenAI } = require("@google/genai");
const NodeCache = require("node-cache");

const cache = new NodeCache({ stdTTL: 3600 });

class AIService {
  constructor() {
    this.apiKey = process.env.GEMINI_API_KEY;
    this.model = process.env.GEMINI_DEFAULT_MODEL || "gemini-2.0-flash";

    if (!this.apiKey) {
      throw new Error("GEMINI_API_KEY is required");
    }

    this.client = new GoogleGenAI({ apiKey: this.apiKey });
    console.log(`✅ Gemini AI Service initialized with model: ${this.model}`);
  }

  getSystemPrompt() {
    return `You are a professional AI consultant with expertise in business, technology, and project management.

## Your Role:
- Provide professional, accurate, and actionable responses
- Use real-time data and current information
- Structure responses with clear headers and bullet points
- Be helpful, concise, and professional

## Response Format:
1. Start with a professional greeting or summary
2. Use clear sections with markdown headers
3. Include specific details, dates, and numbers
4. End with actionable next steps

## For Tenders:
- Search for real-time tender information
- Provide specific details with sources
- Include deadlines and requirements

## For Tasks:
- Provide proven frameworks and methodologies
- Include step-by-step guides
- Suggest tools and best practices

Always maintain a professional and helpful tone.`;
  }

  async generateResponse(query) {
    const cacheKey = query;
    const cached = cache.get(cacheKey);
    if (cached) {
      console.log("✅ Cache hit");
      return cached;
    }

    console.log(`🔄 Generating response for: ${query.substring(0, 50)}...`);

    try {
      const result = await this.client.models.generateContent({
        model: this.model,
        contents: {
          role: "user",
          parts: [{ text: query }],
        },
        config: {
          temperature: 0.7,
          maxOutputTokens: 4096,
          tools: [{ googleSearch: {} }],
          systemInstruction: this.getSystemPrompt(),
        },
      });

      let responseText = result.text || "No response generated";
      let sources = [];

      // Extract sources from search
      if (result.candidates && result.candidates[0]?.groundingMetadata) {
        const grounding = result.candidates[0].groundingMetadata;
        if (grounding.groundingChunks) {
          grounding.groundingChunks.forEach((chunk) => {
            if (chunk.web) {
              sources.push({
                title: chunk.web.title || "Web Source",
                url: chunk.web.uri || "#",
                snippet: chunk.web.snippet || "",
              });
            }
          });
        }
      }

      if (sources.length === 0) {
        sources.push({
          title: "Gemini AI Analysis",
          url: "https://gemini.google.com",
          snippet: "Generated by Google Gemini",
        });
      }

      const response = {
        answer: responseText,
        sources: sources,
        model: this.model,
      };

      cache.set(cacheKey, response);
      console.log(`✅ Response generated successfully`);
      return response;
    } catch (error) {
      console.error("❌ Gemini API Error:", error.message);

      return {
        answer: `# ⚠️ Service Unavailable

I'm having trouble connecting right now. Please try again in a moment.

## Quick alternatives:
- **Google Search**: For immediate answers
- **e-GP Portal**: For tender information
- **Help Center**: For task management guides

---
*Please try your question again.*`,
        sources: [{ title: "Error", url: "#", snippet: error.message }],
        model: this.model,
      };
    }
  }

  async generateStream(query, onChunk, onComplete) {
    try {
      const result = await this.generateResponse(query);
      const words = result.answer.split(" ");
      for (let i = 0; i < words.length; i++) {
        onChunk(words[i] + " ");
        await new Promise((resolve) => setTimeout(resolve, 10));
      }
      onComplete(result.answer, result.sources, result.model);
      return result;
    } catch (error) {
      console.error("Stream Error:", error);
      throw error;
    }
  }

  clearCache() {
    cache.flushAll();
    console.log("🗑️ Cache cleared");
  }
}

module.exports = new AIService();
